version: 0.0
os: linux

files:
  - source: /dealflow
    destination: /dealflow
    overwrite: true

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300

  AfterInstall:
    - location: scripts/after_install.sh
      timeout: 300

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300

permissions:
  - object: /dealflow
    owner: ubuntu
    group: ubuntu
    mode: 755

  - object: scripts/
    owner: ubuntu
    group: ubuntu
    mode: 755
